### ISSUE TITLE
Question: difference between this and debug/elf?

### ISSUE THREAD

**Issue by vsoch** [saferwall/elf#2]
Hiya! I'm interested in parsing ELF with Go (and I've used debug/elf a bit) and I'm wondering what are the main differences here? Thank you!

**Comment by LordNoteworthy** [comment]
Hello @vsoch

As I am not the owner of this code, I myself can't answer this. I am reading the source code today, hopefully I can come back with an answer soon.

Apologies for the delay.

**Comment by vsoch** [comment]
oh wow that's very kind of you, thank you!

**Comment by LordNoteworthy** [comment]
Hello @vsoch 

So far, there is no difference between the packages, they can both parse the header, program headers. sections, relocs, symbols. If this is enough for you, you don't need this one.

The point of this package was to build on top of `debug/elf` and extend parsing portions of a binary that the std library did not support (like what we have done for https://github.com/saferwall/pe). and especially to help in analyzing malicious elf binaries.

Thanks for opening this issue, I will include this question to the FAQ in the `README.md` later. I started digging into the ELF format yesterday, maybe you can check in again 2/3 months later.
