### ISSUE TITLE
Unhandled panic when there are no sections

### ISSUE THREAD

**Issue by lockness-Ko** [saferwall/elf#5]
The parser panics when there are no sections.

Stack trace:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/saferwall/elf.(*Parser).parseELFSections32(0xc000681b48)
	/home/lockness/go/pkg/mod/github.com/saferwall/elf@v0.3.0/parser.go:363 +0x5e6
github.com/saferwall/elf.(*Parser).ParseELFSections(0xc000681b48?, 0x48?)
	/home/lockness/go/pkg/mod/github.com/saferwall/elf@v0.3.0/parser.go:262 +0x56
github.com/saferwall/elf.(*Parser).Parse(0xc000681b48)
	/home/lockness/go/pkg/mod/github.com/saferwall/elf@v0.3.0/parser.go:60 +0x68
```

Sample: https://bazaar.abuse.ch/sample/eee0bb5e4bfacd84056ec6f4175e56afe383d7ffe955c373245247fc82401722/

![image](https://github.com/saferwall/elf/assets/42625905/72215736-7896-4922-a445-01ca26d8fee3)

**Comment by LordNoteworthy** [comment]
@jmpnz can you have a look please ? 😄

**Comment by DawDavis** [comment]
Looked at the underlying error - I think there just needs to be a change to [parser.go:356](https://github.com/saferwall/elf/blob/main/parser.go#L356).

```go
shstrtab, err := sections[p.F.Header64.Shstrndx].Data()
```

to

```go
shstrtab, err := sections[p.F.Header32.Shstrndx].Data()
```

**Comment by LordNoteworthy** [comment]
Thanks @DawDavis 

I pushed a new tag v.0.3.1, can you please check ?

**Comment by DawDavis** [comment]
@LordNoteworthy 
Checked and it looks good to me - should probably have a test case against the 32-bit case, as this should have been detected a while ago. Anyways, I think this story can close - working on my 32bit elf files anyways!

**Comment by LordNoteworthy** [comment]
Yeah 100%, I will get to this project some time soon and I am planning to improve it
